/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minor_project;

/**
 *
 * @author geet
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PRODUCT_INVENTORY = new javax.swing.JButton();
        SUPPLIERS_DEALERS = new javax.swing.JButton();
        CHAIN_STORES = new javax.swing.JButton();
        CUSTOMER_RECORDS = new javax.swing.JButton();
        SALES_TURNOVER = new javax.swing.JButton();
        PERSONNEL_RECORDS = new javax.swing.JButton();
        BILLING = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Futura-Bold", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(197, 0, 92));
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        PRODUCT_INVENTORY.setBackground(new java.awt.Color(244, 243, 244));
        PRODUCT_INVENTORY.setFont(new java.awt.Font("Futura-Bold", 1, 18)); // NOI18N
        PRODUCT_INVENTORY.setForeground(new java.awt.Color(197, 0, 92));
        PRODUCT_INVENTORY.setText("PRODUCT INVENTORY");
        PRODUCT_INVENTORY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRODUCT_INVENTORYMouseClicked(evt);
            }
        });
        PRODUCT_INVENTORY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODUCT_INVENTORYActionPerformed(evt);
            }
        });
        getContentPane().add(PRODUCT_INVENTORY, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 240, 50));

        SUPPLIERS_DEALERS.setBackground(new java.awt.Color(244, 243, 244));
        SUPPLIERS_DEALERS.setFont(new java.awt.Font("Futura-Bold", 1, 18)); // NOI18N
        SUPPLIERS_DEALERS.setForeground(new java.awt.Color(197, 0, 92));
        SUPPLIERS_DEALERS.setText("SUPPLIERS/DEALERS");
        SUPPLIERS_DEALERS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SUPPLIERS_DEALERSMouseClicked(evt);
            }
        });
        SUPPLIERS_DEALERS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPPLIERS_DEALERSActionPerformed(evt);
            }
        });
        getContentPane().add(SUPPLIERS_DEALERS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 240, 50));

        CHAIN_STORES.setBackground(new java.awt.Color(244, 243, 244));
        CHAIN_STORES.setFont(new java.awt.Font("Futura-Bold", 1, 18)); // NOI18N
        CHAIN_STORES.setForeground(new java.awt.Color(197, 0, 92));
        CHAIN_STORES.setText("CHAIN STORES");
        CHAIN_STORES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CHAIN_STORESMouseClicked(evt);
            }
        });
        CHAIN_STORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHAIN_STORESActionPerformed(evt);
            }
        });
        getContentPane().add(CHAIN_STORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 240, 50));

        CUSTOMER_RECORDS.setBackground(new java.awt.Color(244, 243, 244));
        CUSTOMER_RECORDS.setFont(new java.awt.Font("Futura-Bold", 1, 18)); // NOI18N
        CUSTOMER_RECORDS.setForeground(new java.awt.Color(197, 0, 92));
        CUSTOMER_RECORDS.setText("COSTUMER RECORDS");
        CUSTOMER_RECORDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CUSTOMER_RECORDSMouseClicked(evt);
            }
        });
        CUSTOMER_RECORDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUSTOMER_RECORDSActionPerformed(evt);
            }
        });
        getContentPane().add(CUSTOMER_RECORDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 240, 50));

        SALES_TURNOVER.setBackground(new java.awt.Color(244, 243, 244));
        SALES_TURNOVER.setFont(new java.awt.Font("Futura-Bold", 1, 18)); // NOI18N
        SALES_TURNOVER.setForeground(new java.awt.Color(197, 0, 92));
        SALES_TURNOVER.setText("SALES TURNOVER");
        SALES_TURNOVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SALES_TURNOVERMouseClicked(evt);
            }
        });
        SALES_TURNOVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALES_TURNOVERActionPerformed(evt);
            }
        });
        getContentPane().add(SALES_TURNOVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 240, 50));

        PERSONNEL_RECORDS.setBackground(new java.awt.Color(244, 243, 244));
        PERSONNEL_RECORDS.setFont(new java.awt.Font("Futura-Bold", 1, 18)); // NOI18N
        PERSONNEL_RECORDS.setForeground(new java.awt.Color(197, 0, 92));
        PERSONNEL_RECORDS.setText("PERSONNEL RECORDS");
        PERSONNEL_RECORDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PERSONNEL_RECORDSMouseClicked(evt);
            }
        });
        PERSONNEL_RECORDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERSONNEL_RECORDSActionPerformed(evt);
            }
        });
        getContentPane().add(PERSONNEL_RECORDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 240, 50));

        BILLING.setBackground(new java.awt.Color(244, 243, 244));
        BILLING.setFont(new java.awt.Font("Futura-Bold", 1, 18)); // NOI18N
        BILLING.setForeground(new java.awt.Color(197, 0, 92));
        BILLING.setText("BILLING");
        BILLING.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BILLINGMouseClicked(evt);
            }
        });
        BILLING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BILLINGActionPerformed(evt);
            }
        });
        getContentPane().add(BILLING, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 240, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/geet/Desktop/PHARMACY/MENU.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PRODUCT_INVENTORYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODUCT_INVENTORYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRODUCT_INVENTORYActionPerformed

    private void SUPPLIERS_DEALERSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPPLIERS_DEALERSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUPPLIERS_DEALERSActionPerformed

    private void CUSTOMER_RECORDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUSTOMER_RECORDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CUSTOMER_RECORDSActionPerformed

    private void SALES_TURNOVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALES_TURNOVERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SALES_TURNOVERActionPerformed

    private void PERSONNEL_RECORDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERSONNEL_RECORDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PERSONNEL_RECORDSActionPerformed

    private void CHAIN_STORESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHAIN_STORESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHAIN_STORESActionPerformed

    private void BILLINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BILLINGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BILLINGActionPerformed

    
    
    
    private void PRODUCT_INVENTORYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRODUCT_INVENTORYMouseClicked
        new PRODUCT_INVENTORY().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PRODUCT_INVENTORYMouseClicked

    private void CHAIN_STORESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHAIN_STORESMouseClicked
        new CHAIN_STORES().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CHAIN_STORESMouseClicked

    private void SUPPLIERS_DEALERSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUPPLIERS_DEALERSMouseClicked
        new DEALERS_SUPPLIERS().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SUPPLIERS_DEALERSMouseClicked

    private void PERSONNEL_RECORDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PERSONNEL_RECORDSMouseClicked
        new PERSONNEL().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PERSONNEL_RECORDSMouseClicked

    private void CUSTOMER_RECORDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUSTOMER_RECORDSMouseClicked
        new CUSTOMER().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CUSTOMER_RECORDSMouseClicked

    private void BILLINGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLINGMouseClicked
        new BILLING().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BILLINGMouseClicked

    private void SALES_TURNOVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALES_TURNOVERMouseClicked
        new SALES_TURNOVER().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SALES_TURNOVERMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BILLING;
    private javax.swing.JButton CHAIN_STORES;
    private javax.swing.JButton CUSTOMER_RECORDS;
    private javax.swing.JButton PERSONNEL_RECORDS;
    private javax.swing.JButton PRODUCT_INVENTORY;
    private javax.swing.JButton SALES_TURNOVER;
    private javax.swing.JButton SUPPLIERS_DEALERS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
